### ISSUE TITLE
Flooding the actuator with schedule requests seems to confuse the config store

### ISSUE THREAD

**Issue by mikeroup** [VOLTTRON/volttron#1065]

**Comment by craig8** [comment]
@rlutes this is for the error you saw

**Comment by kmonson** [comment]
Real problem: This only happens when the requested reservations start at the time they are made. Each reservation triggers a republish of all the currently active reservations. Each republish gets bigger with each additional reservation. Looking for a way to cut down on the number of publishes in this case.

**Comment by kmonson** [comment]
Fixed in 09470c6e80ffa6c90be508a0cd87be08ec967fa3
