### ISSUE TITLE
Remove hardcoded path in VOLTTRON Central for location of volttron.log

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#129]

**Comment by craig8** [comment]
Logging is now available through websockets 

{"method":"start_reading", "params": {"log_path": "~/.volttron/volttron.log"}}
where the log path is userexpandable.

See https://github.com/VOLTTRON/volttron/blob/master/Agents/VolttronCentralAgent/volttroncentral/webroot/websocket-test.html for an already setup version.

The path is /log rather than /websocket
