### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by srisankethu** [VOLTTRON/volttron#1473]
Tried installing volttron following the instructions given [here](https://volttron.readthedocs.io/en/latest/install.html) but facing an error. I am using Ubuntu 17.04 OS. The error seems to related to proxy. I have set up env variables ``http_proxy``, ``https_proxy``. But still facing the same error. Can someone please help me out?

**Comment by kmonson** [comment]
Are you seeing an error message?

**Comment by srisankethu** [comment]
On running ``python2.7 bootstrap.py --force`` -> https://pastebin.com/hBhk6YHS

**Comment by craig8** [comment]
Thanks for the pastebin.  That will really help.  In addition, I am having one of our students build us a vm using ubuntu 17.04 just like what you are using and we will hopefully see the same issue and then can take corrective action.

I believe since you have already got an env directory you can activate the environment and then run the python bootstrap.py.  This will upgrade the volttron instance without removing the python environment.

**Comment by srisankethu** [comment]
Thank you @craig8 :+1:  ``export all_proxy="https://<proxy>:<port>/"`` worked

**Comment by craig8** [comment]
Awesome....glad that worked for you.
