### ISSUE TITLE
Create Downstream Test with github actions process

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#2867]
Assuming a PR is done provide a mechanism to test a downstream agent using that develop + PR code.

**Comment by bonicim** [comment]
I have verified that we can trigger actions from one repo to another repo. Our use case is to that whenever a volttron-core creates a PR, that event will trigger a workflow on a core agent repo. We need this mechanism to support our CI and release process for Modular Volttron. In my research, I have found that Github Actions supports this mechanism and can implemented in Workflows. Therefore, we can use Github to support our CI and release process for Modular Volttron. Below is an example with links and screenshots of how this works:

Consider two repos, volttron and volttron-openadr-ven-1, in which volttron is the repo creating a 'repository_dispatch' event and volttron-openadr-ven-1 is the repo receiving the aforementioned event. Volttron is considered the 'sender' repo and volttron-openadr-ven-1 is considered the 'receiver' repo. 

Now consider the following flow: 
1. Volttron creates a PR
2. Volttron starts a workflow called 'Repository Dispatch' which creates an event to be picked up by volttron-openadr-ven-1
3. Upon receiving such event, volttron-openadr-ven-1 will start a series of actions such as running tests

Implementation:

Sender workflow: https://github.com/bonicim/volttron/blob/docs/asyncio/.github/workflows/repo-dispatch.yml
Receiver workflow: https://github.com/bonicim/volttron-openadr-ven-1/blob/main/.github/workflows/repo-dispatch-triggered.yaml

![Screen Shot 2022-02-02 at 10 49 56 AM](https://user-images.githubusercontent.com/6901848/152218419-0f0db73f-e3ab-4dfa-807b-5ff2f66ed996.png)

![Screen Shot 2022-02-02 at 10 50 28 AM](https://user-images.githubusercontent.com/6901848/152218480-f66082ab-dff0-4d98-b967-f88afe763177.png)

Notes:
* The implementation uses a third-party Github action, [Repository Dispatch](https://github.com/marketplace/actions/repository-dispatch) to create this mechanism
* If we want to create our action (i.e. reinvent the wheel), we can use Github Action's [dispatches](https://docs.github.com/en/rest/reference/actions#create-a-workflow-dispatch-event) 
* The implementation requires the use of Personal Access Tokens(PAT) with repo and write privileges. Note that I used my personal account to verify the workflows because I had full admin privileges to create and add PAT's. To do this on Volttron-specific repos, a Volttron team member with admin privileges (e.g. @craig8 or @shwethanidd) will have to create and add PAT's as needed. 

Questions:
* What happens if a test fails on a downstream repo? Should the upstream repo fail its CI workflow in response to a failed test in a downstream repo?

**Comment by schandrika** [comment]
This is good. 
1. Question- can it trigger more than 1 downstream test?
2. Yes if the downstream test fails then the upstream should either me marked as failed with the correct reason, or at least get a notification so that the reviewer assigned to the PR can take a look at the failing test cases

**Comment by craig8** [comment]
@schandrika I get notifications from all the failed actions... you can to :) 
From there I agree we can divide and fix....I don't think that just because a downstream project fails it should be marked as a failure I think it depends on the repository and whether we are looking at regressions or agent failures.

So lets think about that more.

**Comment by craig8** [comment]
I added a secret for PAT.  We can talk about permissions at todays work meeting.

**Comment by bonicim** [comment]
@schandrika, responses below.
> This is good.
> 
> 1. Question- can it trigger more than 1 downstream test?

It can trigger any number of tests among any number of repos. The third-party  action allows for [triggers on multiple repos](https://github.com/marketplace/actions/repository-dispatch#dispatch-to-multiple-repositories). And in each corresponding repo, we can write a Workflow than can respond to a dispatch event and run any number of tests within that repo. 

> 2. Yes if the downstream test fails then the upstream should either me marked as failed with the correct reason, or at least get a notification so that the reviewer assigned to the PR can take a look at the failing test cases

For this workflow to occur, we can design the downstream Workflow to trigger another dispatch to the original repo triggering the first dipatch.

**Comment by bonicim** [comment]
> I added a secret for PAT. We can talk about permissions at todays work meeting.

@craig8 Clarification on the PAT. Is there a PAT in place for the new volttron-core repo? From the Team's message, I understand that there's now PAT's for volttron and volttron-openadr.

**Comment by craig8** [comment]
volttron, volttron-core, and openadr-ven
