### ISSUE TITLE
Strange issue with vc GUI

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#571]
How come all building10?
![3 points](https://cloud.githubusercontent.com/assets/3979063/15480074/676b35d0-20d8-11e6-940c-ea02cf430471.png)

**Comment by jchap-pnnl** [comment]
It's the ZoneTemperature point for three different devices that are all in BUILDING10. If you hover over the chart, you get the breakdown:

![image](https://cloud.githubusercontent.com/assets/15679599/15481106/b95c2d86-20dd-11e6-9f0e-35cefc624c59.png)

The real issue is, the chart's legend labels probably need to be improved. A quick option is to reverse the order so the device is first and the platform is last, meaning the platform part would be truncated if there wasn't enough room, not the device.

We may be able to come up with a different legend label altogether that doesn't truncate any of the information, but that will take some doing.

**Comment by jchap-pnnl** [comment]
Also, you get the whole device path when hovering over the legend label:

![image](https://cloud.githubusercontent.com/assets/15679599/15481316/b904a06a-20de-11e6-9396-47d8d6ebe5f7.png)

**Comment by craig8** [comment]
I see the issue thanks...closing this as a mis diagnosis.
