### ISSUE TITLE
Too many status updates when login or refresh

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron#630]
I have a couple of platforms that are mis behaving.  I don't think refreshing the page should tell  me that again nor when I login.  The proper place for this is the tree not the status bar I think.

![2016-06-10 18_29_19-volttron central beta](https://cloud.githubusercontent.com/assets/3979063/15982330/56a913e2-2f39-11e6-9e64-483f71aeb080.png)

**Comment by craig8** [comment]
@jchap-pnnl where are we on this issue?  I would like to not have this show up on the rc1 branch.

To reproduce you create a vc and vcp (same instance or otherwise) then register or rely on the autoregister.  Then turn the vcp off and hit refresh.

**Comment by jchap-pnnl** [comment]
I'll get it removed shortly. I think we could say the larger issue is, only show the status message in response to user actions. Registering or deregistering platform fails, alert the user. Starting, stopping, or removing agent fails, alert the user.

So another place to remove the message would be when the charts fail to refresh because the historian stopped running or something like that. The message can be similarly distracting. But as you've pointed out, it might be helpful to add an indicator to the charts to show that the data isn't getting updated. I'll create a separate issue for that.

**Comment by jhaack** [comment]
@jchap-pnnl  Close if fixed

**Comment by jchap-pnnl** [comment]
It appears this hasn't been fixed -- at least, not in develop. I'll fix it in the config device branch, unless we need it quicker.

**Comment by craig8** [comment]
Config devices will work.  That is going to morph into 4.0.1 branch soon.
