### ISSUE TITLE
Potential memory Leaks

### ISSUE THREAD

**Issue by fstshrk** [VOLTTRON/volttron#669]
Valgrind checks on VOLTTRON show slow memory leaks.

**Comment by kmonson** [comment]
This is a "feature" of Python.  Apparently it's a false report based on how Python manages it's own memory. In order to get Valgrind to work correctly you have to recompile Python with certain switches to turn PyMalloc off.

There is an entire write up about using Valgrind to debug the Python interpreter here: https://github.com/python/cpython/blob/2.7/Misc/README.valgrind
