### ISSUE TITLE
Update all references to the "applications" folder in documenation

### ISSUE THREAD

**Issue by jhaack** [VOLTTRON/volttron#876]
Applications moved to their own repo. Find and update places where the old folder is referred to. Make a page discussing the new model.

**Comment by mikeroup** [comment]
The following scripts all use the applications directory to check to see if the script if being run from the source root. We changed this a long time ago for make-agent.sh. Since these still look for the applications directory maybe nobody is using them?
```
scripts/historian-scripts/start-historian-sqlite.sh
scripts/historian-scripts/start-historian-openeis.sh
scripts/historian-scripts/start-historian-mysql.sh

scripts/core/start_historian.sh
scripts/core/start_platform.sh
```

These scripts use the are for installing agents in the applications directory with the make agent script and could probably be removed. 
```
scripts/scalability-testing/make-masternode
scripts/scalability-testing/make-modelnode
```
